[server]
port = 18888
domain = "http://127.0.0.1:18888"
storage = "local"

[sql]
user = "go_admin"
pass = "123123"
host = "127.0.0.1"
dbName = "go_admin"
port = 13306
maxIdleConns = 10
maxOpenConns = 100

[log]
directory = "log"
enableConsoleOut= true
enableFileOut = false
enableMixedSave = true
enableStacktrace = false
level = "info"
maxAge = 0
maxSize = 1024
stacktraceLevel = "fatal"

[redis]
host = "127.0.0.1"
port = 6379
password = ""
db = 0

[sentry]
dsn = "" # Add your Sentry DSN here