[server]
port = 18888

[sql]
user = "root"
pass = "root"
host = "127.0.0.1"
dbName = "go-admin"
port = 3306
maxIdleConns = 10
maxOpenConns = 100

[log]
directory = "log"
enableConsoleOut= true
enableFileOut = false
enableMixedSave = true
enableStacktrace = false
level = "info"
maxAge = 0
maxSize = 1024
stacktraceLevel = "fatal"