[server]
port = 18888
domain = "http://127.0.0.1:18888"
storage = "local"
env = 0

[sql]
user = "go_admin"
pass = "go_admin"
host = "127.0.0.1"
dbName = "go_admin"
port = 3306
maxIdleConns = 10
maxOpenConns = 100

[log]
directory = "log"
enableConsoleOut= true
enableFileOut = false
enableMixedSave = true
enableStacktrace = false
level = "info"
maxAge = 0
maxSize = 1024
stacktraceLevel = "fatal"

[redis]
host = "localhost"
port = 6379
password = ""
db = 0
poolSize = 10

[sqlite]
path = "./data/sqlite.db"
maxIdleConns = 10
maxOpenConns = 100
enableWAL = true
busyTimeout = 5000